pullRequestOpened: >
   Acabas de iniciar tu primer pull request en este repositorio, ¡bien! :thumbsup:


   Al ser un repositorio en el que vamos a trabajar toda la clase, es necesario que alguien revise los cambios que propones antes de integrarlos. Para este primer ejercicio, haz clic en **Reviewers** a la derecha y selecciona a Miren de la lista.


   Si recibes comentarios o alguna sugerencia de cambio, realiza esos cambios en tu ordenador y vuelve a hacer push. Los commits aparecerán aquí debajo.


   Cuando Miren apruebe tus modificaciones, podrás incorporar tus cambios a este repositorio haciendo clic en el botón **Merge pull request** (que estará verde).


   ¡No dudes en dejar un comentario aquí mismo si tienes alguna pregunta!


#  For the first assignment, adding name to directory:

#  Acabas de iniciar un pull request para integrar los cambios que has ido realizando en tu repositorio personal, ¡bien! :thumbsup:
#
#
#  Recuerda asignar los metadatos correctamente (a la derecha):
#
#
#  - En **Reviewers**, selecciona a las demás personas que han trabajado contigo en esta unidad
#
#  - En **Milestones**, asigna este pull request al borrador correspondiente (_Estrategia_, _Alcance_, _Estructura_, _Esqueleto_, _Superficie_)
#
#
#  Ahora podéis realizar los comentarios necesarios sobre estas modificaciones aquí debajo, y tú puedes seguir realizando cambios al branch de tu copia personal. Cuando la persona encargada de Control considere que esta aportación está como para integrar en el borrador, puede dar el OK al review, y entonces la profesora humana podrá hacer merge e integrar las modificaciones en el repositorio central.
#
#
#  Como siempre, si tenéis dudas, mencionad a Miren en vuestros comentarios.